version: "2.1"
services:
  jupyter:
    container_name: ai-notebook
    image: tensorflow/tensorflow:latest-gpu-jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./lafontaine:/tf
      - ./lexique:/lexique
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
